export { default as backgroundLight } from './images/background-light.jpg'
export { default as backgroundDark } from './images/background-dark.png'
export { default as mac1 } from './images/mac1.jpeg'
export { default as mac2 } from './images/mac2.jpeg'

export { default as homeIcon } from './icons/homeIcon.svg'
export { default as contactIcon } from './icons/contactIcon.svg'
export { default as languageIcon } from './icons/languageIcon.svg'
export { default as portfolioIcon } from './icons/portfolioIcon.svg'
export { default as priceIcon } from './icons/priceIcon.svg'
export { default as serviceIcon } from './icons/serviceIcon.svg'
export { default as sunIcon } from './icons/sunIcon.svg'
export { default as moonIcon } from './icons/moonIcon.svg'
export { default as chevronDownIcon } from './icons/chevronDownIcon.svg'