export { default as Home } from './Home'
export { default as Sidebar } from './Sidebar'
export { default as Footer } from './Footer'
export { default as Portfolio } from './Portfolio'
export { default as Services } from './Services'